name: Error
description: Reporte del error
body:
  - type: markdown
    attributes:
      value: Antes de abrir un error, mira si el error ya esta reportado.
  - type: textarea
    id: navegador
    attributes:
      label: Navegador
      description: ¿En que navegador o navegadores sucede?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descripción del error
      description: ¿Que sucede?
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: pasos para reproducir
      description: ¿Que pasos se requieren para reproducir el error?
    validations:
      required: true
